/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                'inverse-surface': '#27313f',
                'secondary-container': '#c4a7ff',
                'tertiary': '#7d3d00',
                'on-error': '#ffffff',
                'primary-container': '#7c3aed',
                'surface-container-low': '#eff4ff',
                'on-secondary-fixed': '#25005a',
                'on-secondary-container': '#523787',
                'secondary': '#6a4fa0',
                'on-primary-container': '#ede0ff',
                'on-surface-variant': '#4a4455',
                'on-tertiary': '#ffffff',
                'surface-bright': '#f8f9ff',
                'surface-tint': '#732ee4',
                'on-tertiary-container': '#ffe0cd',
                'on-surface': '#121c2a',
                'on-background': '#121c2a',
                'secondary-fixed': '#eaddff',
                'surface-container-highest': '#d9e3f6',
                'surface-variant': '#d9e3f6',
                'outline': '#7b7487',
                'on-primary-fixed-variant': '#5a00c6',
                'primary': '#630ed4',
                'on-error-container': '#93000a',
                'on-primary-fixed': '#25005a',
                'surface-dim': '#d0dbed',
                'surface-container': '#e6eeff',
                'surface': '#f8f9ff',
                'outline-variant': '#ccc3d8',
                'error-container': '#ffdad6',
                'background': '#f8f9ff',
                'inverse-primary': '#d2bbff',
                'tertiary-container': '#a15100',
                'inverse-on-surface': '#eaf1ff',
                'error': '#ba1a1a',
                'primary-fixed': '#eaddff',
                'on-primary': '#ffffff',
                'surface-container-lowest': '#ffffff',
                'on-secondary': '#ffffff',
                'primary-fixed-dim': '#d2bbff',
            },
            borderRadius: {
                DEFAULT: '1rem',
                lg: '2rem',
                xl: '3rem',
                full: '9999px',
            },
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [],
};